basePath: /api/v1
info:
  contact: {}
  description: This is a simple user registration and auth server with automatic jwt
    renewal.
  title: Gorm User & Auth
  version: 0.0.3
paths: {}
swagger: "2.0"
